# Generated by Django 3.1 on 2020-08-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
